module Catorax
  module ScientificMetadata
    extend ActiveSupport::Concern

    included do
      # Add properties that would be appropriate for use in objects of the Scientific Work Type, such as:
      # property :digital_specifications, predicate: RDF::Vocab::DC11.format
      property :accepted_name_usage, predicate: ::RDF::Vocab::DWC.acceptedNameUsage
      property :accepted_name_usage_id, predicate: ::RDF::Vocab::DWC.acceptedNameUsageID
      property :according_to, predicate: ::RDF::Vocab::DWC.accordingTo
      property :associated_media, predicate: ::RDF::Vocab::DWC.associatedMedia
      property :associated_occurrences, predicate: ::RDF::Vocab::DWC.associatedOccurrences
      property :associated_organisms, predicate: ::RDF::Vocab::DWC.associatedOrganisms
      property :associated_references, predicate: ::RDF::Vocab::DWC.associatedReferences
      property :associated_sequences, predicate: ::RDF::Vocab::DWC.associatedSequences
      property :associated_taxa, predicate: ::RDF::Vocab::DWC.associatedTaxa
      property :basis_of_record, predicate: ::RDF::Vocab::DWC.basisOfRecord
      property :bed, predicate: ::RDF::Vocab::DWC.bed
      property :behavior, predicate: ::RDF::Vocab::DWC.behavior
      property :catalog_number, predicate: ::RDF::Vocab::DWC.catalogNumber
      # 'class' is protected
      property :dwcclass, predicate: ::RDF::Vocab::DWC.class
      property :collection_code, predicate: ::RDF::Vocab::DWC.collectionCode
      property :collection_id, predicate: ::RDF::Vocab::DWC.collectionID
      property :continent, predicate: ::RDF::Vocab::DWC.continent
      property :coordinate_precision, predicate: ::RDF::Vocab::DWC.coordinatePrecision
      property :coordinate_uncertainty_in_meters, predicate: ::RDF::Vocab::DWC.coordinateUncertaintyInMeters
      property :country, predicate: ::RDF::Vocab::DWC.country
      property :country_code, predicate: ::RDF::Vocab::DWC.countryCode
      property :county, predicate: ::RDF::Vocab::DWC.county
      property :data_generalizations, predicate: ::RDF::Vocab::DWC.dataGeneralizations
      property :dataset_id, predicate: ::RDF::Vocab::DWC.datasetID
      property :dataset_name, predicate: ::RDF::Vocab::DWC.datasetName
      property :date_identified, predicate: ::RDF::Vocab::DWC.dateIdentified
      property :day, predicate: ::RDF::Vocab::DWC.day
      property :decimal_latitude, predicate: ::RDF::Vocab::DWC.decimalLatitude
      property :decimal_longitude, predicate: ::RDF::Vocab::DWC.decimalLongitude
      property :disposition, predicate: ::RDF::Vocab::DWC.disposition
      property :dynamic_properties, predicate: ::RDF::Vocab::DWC.dynamicProperties
      property :earliest_age_or_lowest_stage, predicate: ::RDF::Vocab::DWC.earliestAgeOrLowestStage
      property :earliest_eon_or_lowest_eonothem, predicate: ::RDF::Vocab::DWC.earliestEonOrLowestEonothem
      property :earliest_epoch_or_lowest_series, predicate: ::RDF::Vocab::DWC.earliestEpochOrLowestSeries
      property :earliest_era_or_lowest_erathem, predicate: ::RDF::Vocab::DWC.earliestEraOrLowestErathem
      property :earliest_period_or_lowest_system, predicate: ::RDF::Vocab::DWC.earliestPeriodOrLowestSystem
      property :end_day_of_year, predicate: ::RDF::Vocab::DWC.endDayOfYear
      property :establishment_means, predicate: ::RDF::Vocab::DWC.establishmentMeans
      property :event_date, predicate: ::RDF::Vocab::DWC.eventDate
      property :event_id, predicate: ::RDF::Vocab::DWC.eventID
      property :event_remarks, predicate: ::RDF::Vocab::DWC.eventRemarks
      property :event_time, predicate: ::RDF::Vocab::DWC.eventTime
      property :family, predicate: ::RDF::Vocab::DWC.family
      property :field_notes, predicate: ::RDF::Vocab::DWC.fieldNotes
      property :field_number, predicate: ::RDF::Vocab::DWC.fieldNumber
      property :footprint_srs, predicate: ::RDF::Vocab::DWC.footprintSRS
      property :footprint_spatial_fit, predicate: ::RDF::Vocab::DWC.footprintSpatialFit
      property :footprint_wkt, predicate: ::RDF::Vocab::DWC.footprintWKT
      property :formation, predicate: ::RDF::Vocab::DWC.formation
      property :genus, predicate: ::RDF::Vocab::DWC.genus
      property :geodetic_datum, predicate: ::RDF::Vocab::DWC.geodeticDatum
      property :geological_context_id, predicate: ::RDF::Vocab::DWC.geologicalContextID
      property :georeference_protocol, predicate: ::RDF::Vocab::DWC.georeferenceProtocol
      property :georeference_remarks, predicate: ::RDF::Vocab::DWC.georeferenceRemarks
      property :georeference_sources, predicate: ::RDF::Vocab::DWC.georeferenceSources
      property :georeference_verification_status, predicate: ::RDF::Vocab::DWC.georeferenceVerificationStatus
      property :georeferenced_by, predicate: ::RDF::Vocab::DWC.georeferencedBy
      property :georeferenced_date, predicate: ::RDF::Vocab::DWC.georeferencedDate
      property :group, predicate: ::RDF::Vocab::DWC.group
      property :habitat, predicate: ::RDF::Vocab::DWC.habitat
      property :higher_classification, predicate: ::RDF::Vocab::DWC.higherClassification
      property :higher_geography, predicate: ::RDF::Vocab::DWC.higherGeography
      property :higher_geographyID, predicate: ::RDF::Vocab::DWC.higherGeographyID
      property :highest_biostratigraphic_zone, predicate: ::RDF::Vocab::DWC.highestBiostratigraphicZone
      property :identification_id, predicate: ::RDF::Vocab::DWC.identificationID
      property :identification_qualifier, predicate: ::RDF::Vocab::DWC.identificationQualifier
      property :identification_references, predicate: ::RDF::Vocab::DWC.identificationReferences
      property :identification_remarks, predicate: ::RDF::Vocab::DWC.identificationRemarks
      property :identification_verification_status, predicate: ::RDF::Vocab::DWC.identificationVerificationStatus
      property :identified_by, predicate: ::RDF::Vocab::DWC.identifiedBy
      property :individual_count, predicate: ::RDF::Vocab::DWC.individualCount
      property :information_withheld, predicate: ::RDF::Vocab::DWC.informationWithheld
      property :infraspecific_epithet, predicate: ::RDF::Vocab::DWC.infraspecificEpithet
      property :institution_code, predicate: ::RDF::Vocab::DWC.institutionCode
      property :institution_id, predicate: ::RDF::Vocab::DWC.institutionID
      property :island, predicate: ::RDF::Vocab::DWC.island
      property :island_group, predicate: ::RDF::Vocab::DWC.islandGroup
      property :kingdom, predicate: ::RDF::Vocab::DWC.kingdom
      property :latest_age_or_highest_stage, predicate: ::RDF::Vocab::DWC.latestAgeOrHighestStage
      property :latest_eon_or_highest_eonothem, predicate: ::RDF::Vocab::DWC.latestEonOrHighestEonothem
      property :latest_epoch_or_highest_series, predicate: ::RDF::Vocab::DWC.latestEpochOrHighestSeries
      property :latest_era_or_highest_erathem, predicate: ::RDF::Vocab::DWC.latestEraOrHighestErathem
      property :latest_period_or_highest_system, predicate: ::RDF::Vocab::DWC.latestPeriodOrHighestSystem
      property :life_stage, predicate: ::RDF::Vocab::DWC.lifeStage
      property :lithostratigraphic_terms, predicate: ::RDF::Vocab::DWC.lithostratigraphicTerms
      property :locality, predicate: ::RDF::Vocab::DWC.locality
      property :location_according_to, predicate: ::RDF::Vocab::DWC.locationAccordingTo
      property :location_id, predicate: ::RDF::Vocab::DWC.locationID
      property :location_remarks, predicate: ::RDF::Vocab::DWC.locationRemarks
      property :lowest_biostratigraphic_zone, predicate: ::RDF::Vocab::DWC.lowestBiostratigraphicZone
      property :material_sample_id, predicate: ::RDF::Vocab::DWC.materialSampleID
      property :maximum_depth_in_meters, predicate: ::RDF::Vocab::DWC.maximumDepthInMeters
      property :maximum_distance_above_surface_in_meters, predicate: ::RDF::Vocab::DWC.maximumDistanceAboveSurfaceInMeters
      property :maximum_elevation_in_meters, predicate: ::RDF::Vocab::DWC.maximumElevationInMeters
      property :measurement_accuracy, predicate: ::RDF::Vocab::DWC.measurementAccuracy
      property :measurement_determined_by, predicate: ::RDF::Vocab::DWC.measurementDeterminedBy
      property :measurement_determined_date, predicate: ::RDF::Vocab::DWC.measurementDeterminedDate
      property :measurement_id, predicate: ::RDF::Vocab::DWC.measurementID
      property :measurement_method, predicate: ::RDF::Vocab::DWC.measurementMethod
      property :measurement_remarks, predicate: ::RDF::Vocab::DWC.measurementRemarks
      property :measurement_type, predicate: ::RDF::Vocab::DWC.measurementType
      property :measurement_unit, predicate: ::RDF::Vocab::DWC.measurementUnit
      property :measurement_value, predicate: ::RDF::Vocab::DWC.measurementValue
      property :member, predicate: ::RDF::Vocab::DWC.member
      property :minimum_depth_in_meters, predicate: ::RDF::Vocab::DWC.minimumDepthInMeters
      property :minimum_distance_above_surface_in_meters, predicate: ::RDF::Vocab::DWC.minimumDistanceAboveSurfaceInMeters
      property :minimum_elevation_in_meters, predicate: ::RDF::Vocab::DWC.minimumElevationInMeters
      property :month, predicate: ::RDF::Vocab::DWC.month
      property :municipality, predicate: ::RDF::Vocab::DWC.municipality
      property :name_according_to, predicate: ::RDF::Vocab::DWC.nameAccordingTo
      property :name_according_to_id, predicate: ::RDF::Vocab::DWC.nameAccordingToID
      property :name_published_in, predicate: ::RDF::Vocab::DWC.namePublishedIn
      property :name_published_in_id, predicate: ::RDF::Vocab::DWC.namePublishedInID
      property :name_published_in_year, predicate: ::RDF::Vocab::DWC.namePublishedInYear
      property :nomenclatural_code, predicate: ::RDF::Vocab::DWC.nomenclaturalCode
      property :nomenclatural_status, predicate: ::RDF::Vocab::DWC.nomenclaturalStatus
      property :occurrence_id, predicate: ::RDF::Vocab::DWC.occurrenceID
      property :occurrence_remarks, predicate: ::RDF::Vocab::DWC.occurrenceRemarks
      property :occurrence_status, predicate: ::RDF::Vocab::DWC.occurrenceStatus
      property :order, predicate: ::RDF::Vocab::DWC.order
      property :organism_id, predicate: ::RDF::Vocab::DWC.organismID
      property :organism_name, predicate: ::RDF::Vocab::DWC.organismName
      property :organism_remarks, predicate: ::RDF::Vocab::DWC.organismRemarks
      property :organism_scope, predicate: ::RDF::Vocab::DWC.organismScope
      property :original_name_usage, predicate: ::RDF::Vocab::DWC.originalNameUsage
      property :original_name_usage_id, predicate: ::RDF::Vocab::DWC.originalNameUsageID
      property :other_catalog_numbers, predicate: ::RDF::Vocab::DWC.otherCatalogNumbers
      property :owner_institution_code, predicate: ::RDF::Vocab::DWC.ownerInstitutionCode
      property :parent_name_usage, predicate: ::RDF::Vocab::DWC.parentNameUsage
      property :parent_name_usage_id, predicate: ::RDF::Vocab::DWC.parentNameUsageID
      property :phylum, predicate: ::RDF::Vocab::DWC.phylum
      property :point_radius_spatial_fit, predicate: ::RDF::Vocab::DWC.pointRadiusSpatialFit
      property :preparations, predicate: ::RDF::Vocab::DWC.preparations
      property :previous_identifications, predicate: ::RDF::Vocab::DWC.previousIdentifications
      property :record_number, predicate: ::RDF::Vocab::DWC.recordNumber
      property :recorded_by, predicate: ::RDF::Vocab::DWC.recordedBy
      property :related_resource_id, predicate: ::RDF::Vocab::DWC.relatedResourceID
      property :relationship_according_to, predicate: ::RDF::Vocab::DWC.relationshipAccordingTo
      property :relationship_established_date, predicate: ::RDF::Vocab::DWC.relationshipEstablishedDate
      property :relationship_of_resource, predicate: ::RDF::Vocab::DWC.relationshipOfResource
      property :relationship_remarks, predicate: ::RDF::Vocab::DWC.relationshipRemarks
      property :reproductive_condition, predicate: ::RDF::Vocab::DWC.reproductiveCondition
      property :resource_id, predicate: ::RDF::Vocab::DWC.resourceID
      property :resource_relationship_id, predicate: ::RDF::Vocab::DWC.resourceRelationshipID
      property :sampling_effort, predicate: ::RDF::Vocab::DWC.samplingEffort
      property :sampling_protocol, predicate: ::RDF::Vocab::DWC.samplingProtocol
      property :scientific_name, predicate: ::RDF::Vocab::DWC.scientificName
      property :scientific_name_authorship, predicate: ::RDF::Vocab::DWC.scientificNameAuthorship
      property :scientific_name_id, predicate: ::RDF::Vocab::DWC.scientificNameID
      property :sex, predicate: ::RDF::Vocab::DWC.sex
      property :specific_epithet, predicate: ::RDF::Vocab::DWC.specificEpithet
      property :start_day_of_year, predicate: ::RDF::Vocab::DWC.startDayOfYear
      property :state_province, predicate: ::RDF::Vocab::DWC.stateProvince
      property :subgenus, predicate: ::RDF::Vocab::DWC.subgenus
      property :taxon_concept_id, predicate: ::RDF::Vocab::DWC.taxonConceptID
      property :taxon_id, predicate: ::RDF::Vocab::DWC.taxonID
      property :taxon_rank, predicate: ::RDF::Vocab::DWC.taxonRank
      property :taxon_remarks, predicate: ::RDF::Vocab::DWC.taxonRemarks
      property :taxonomic_status, predicate: ::RDF::Vocab::DWC.taxonomicStatus
      property :type_status, predicate: ::RDF::Vocab::DWC.typeStatus
      property :verbatim_coordinate_system, predicate: ::RDF::Vocab::DWC.verbatimCoordinateSystem
      property :verbatim_coordinates, predicate: ::RDF::Vocab::DWC.verbatimCoordinates
      property :verbatim_depth, predicate: ::RDF::Vocab::DWC.verbatimDepth
      property :verbatim_elevation, predicate: ::RDF::Vocab::DWC.verbatimElevation
      property :verbatim_event_date, predicate: ::RDF::Vocab::DWC.verbatimEventDate
      property :verbatim_latitude, predicate: ::RDF::Vocab::DWC.verbatimLatitude
      property :verbatim_locality, predicate: ::RDF::Vocab::DWC.verbatimLocality
      property :verbatim_longitude, predicate: ::RDF::Vocab::DWC.verbatimLongitude
      property :verbatim_srs, predicate: ::RDF::Vocab::DWC.verbatimSRS
      property :verbatim_taxon_rank, predicate: ::RDF::Vocab::DWC.verbatimTaxonRank
      property :vernacular_name, predicate: ::RDF::Vocab::DWC.vernacularName
      property :water_body, predicate: ::RDF::Vocab::DWC.waterBody
      property :year, predicate: ::RDF::Vocab::DWC.year
    end
  end
end