# Generated by hyrax:models:install
class FileSet < ActiveFedora::Base
  include ::Hyrax::FileSetBehavior

  self.indexer = ESSI::FileSetIndexer

  # This model includes metadata properties specific to file sets
  include ESSI::FileSetMetadata

  def ocr_language
    [language.entries,
     parent&.language&.entries,
     ESSI.config.dig(:essi, :hocr_language),
     'eng'].map { |l| Tesseract.try_languages(l) }.select(&:present?).first
  end
end
