# Generated by hyrax:models:install
class FileSet < ActiveFedora::Base
  include ::Hyrax::FileSetBehavior

  def ocr_language
    return try_language(language.entries).join("+") if
     try_language(language.entries).present?
    return try_language(self.parent.language.entries).join("+") if
     try_language(self.parent.language.entries).present?
    return try_language(ESSI.config.dig(:essi, :fileset_language)).join("+") if
     try_language(ESSI.config.dig(:essi, :fileset_language)).present?
    'eng'
  end

  private

  def try_language(language)
    (language || []).reject do |lang|
      Tesseract.languages[lang.to_sym].nil?
    end
  end
end
